version: '3.8'
services:
  db:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=bank_system
      - PGDATA=/var/lib/postgresql/data
    ports:
      - '5432:5432'
  rest-server:
    build: ./REST-Server
    container_name: bank-system-server
    ports:
      - "8888:80"
    depends_on:
      - db
    volumes:
      - /Users/ahmednasser/.m2:/root/.m2/
    environment:
      - SERVER_PORT=80
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=bank_system
      - DB_USERNAME=postgres
      - DB_PASSWORD=mypassword
    restart: unless-stopped